name: Bug
description: Something isn't working correctly
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief description of the bug.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is happening? Include error messages, unexpected behavior, and steps to reproduce if applicable.
    validations:
      required: true
  - type: textarea
    id: fix
    attributes:
      label: Fix
      description: Proposed fix or investigation steps. Use task checkboxes (`- [ ]`) for actionable items.
      value: |
        - [ ]
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: How was this discovered? What environment, host, or workflow triggered it?
    validations:
      required: false
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      description: How do we verify the fix? Concrete, verifiable conditions.
      value: |
        - [ ]
    validations:
      required: true
