name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: tskovlund/.github/.github/workflows/nix-check.yml@562e63fbc2a3a2a4c959ab8c4899aa800976e0e6 # main
    with:
      platforms: '["ubuntu-latest", "macos-latest"]'
